[package]
name = "zero2prod"
version = "0.1.0"
authors = ["zZKato <michelevig@protonmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "3.3.2"
actix-rt = "2.0.2"
reqwest = "0.11.0"

[dev-dependencies]
tokio = "1.2.0"
